Add folder structure for variants
Informaticore/SuperPower pull request #3
Opened 2020-09-24 19:13 UTC by Informaticore

2020-09-24 19:23 UTC, wassfila requested changes
I also suggest to make the directories a little bit easier to read : I think we can afford full names in directories such as 
SuperPower-LowCost or avoid repeating SuperPower everywhere as it's already in the name of the parent directory
variation-LowCost, variation-no-uC, variation-uC-default or variation-uC-main, or just uC-LowCost, no-uC, ...

2020-09-24 19:24 UTC, wassfila commented
Note Vincent suggested underscode instead of dah, but I don't mind that.
varitaion-LowCost
Variation_LowCost
Variant_LowCost
as long as we stay a bit consistent

2020-09-25 06:59 UTC, Informaticore commented
Changed folders. I removed the no uC version because we can add it later.

2020-09-25 16:19 UTC, wassfila approved these changes, later dismissed

2020-09-25 20:06 UTC, merged